### ISSUE TITLE
Need retry/timeout

### ISSUE THREAD

**Issue by clburlison** [airbnb/gosal#33]
Right now if your server doesn't respond due to network errors or the server simply isn't "on" gosal doesn't properly retry, timeout, or alert.

- [x] Implement a timeout of 30sec 
- [ ] Retry 3 times before fulling failing?
- [x] Write these states to stdout/stderr

Eventually I could see a client side log instead of just stdout.

**Comment by grahamgilbert** [comment]
I vote for a 30 sec timeout and eat any errors. The laptop being offline isn’t an “error” state. Or if some do care about this maybe a config option if you are using this to report on servers or other devices that are always online (but Sal isn’t a monitoring tool, so I don’t think this is really a valid reason)

**Comment by groob** [comment]
How about a local buffer?

**Comment by clburlison** [comment]
I'm closing this since #36 addressed my concerns. We now have a timeout and we now print to stdout with:

```powershell
gosal did not complete: checkin: failed to checkin: Post https://server_url/checkin/:
dial tcp 10.10.10.10: connectex: No connection could be made because the target machine actively refused it.
```
