### ISSUE TITLE
add CI for tests

### ISSUE THREAD

**Issue by groob** [airbnb/gosal#8]
I'd like to send a PR that runs the tests on CI. What do you think?

Do you have a preference for CircleCI, Travis or something else? Happy to work with any of the free CIs out there.

**Comment by ljharb** [comment]
travis-ci is what airbnb tends to use; it's wired up for this project now as soon as a .travis.yml lands :-D

**Comment by bdemetris** [comment]
@groob ive taken a shot at implementing a linter in the `Makefile` and so far, but i haven't gotten around to perfecting `make build` (so far i've been able to implement `make deps && make test`.  if you have any other suggestions, please do file a PR im interested if you know of some nice go magic here 😄

**Comment by groob** [comment]
Looks like Travis is now running!
